<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitffe7077ae97fbc59c0c3eb2009d52828
{
    public static $prefixLengthsPsr4 = array (
        'T' => 
        array (
            'Twilio\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Twilio\\' => 
        array (
            0 => __DIR__ . '/..' . '/twilio/sdk/src/Twilio',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitffe7077ae97fbc59c0c3eb2009d52828::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitffe7077ae97fbc59c0c3eb2009d52828::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
